# This makefile generated by Armando Baños Pascual

# Dependencies
#
# libcrypt, libglib-2.0, libwebsockets

# variables

OBJECTS = splashd.o conf.o util.o linux.o gateway.o firewall.o http.o websck.o passive.o
INCLUDES = -I. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include
WARNINGS = -Wall
LIBRARYPATH = -L/usr/lib -L/lib
LIBRARIES = -lglib-2.0 -lcrypt -lwebsockets
CC = g++
EXECUTABLE = splashd
CONFFILE = nocat.conf


DEBUG_YES = -g
DEBUG_NO =

#DEBUG = $(DEBUG_YES)
DEBUG = $(DEBUG_NO)

OPTIMIZATIONS_0 =
OPTIMIZATIONS_1 = -O1
OPTIMIZATIONS_2 = -O2
OPTIMIZATIONS_3 = -O3
#optimization for size
OPTIMIZATIONS_s = -Os

OPTIMIZATIONS = $(OPTIMIZATIONS_3)

OUTPUT = -o $(EXECUTABLE)

# Rules

splashd : $(OBJECTS)
	$(CC) $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) $(OUTPUT) $(OBJECTS) $(LIBRARYPATH) $(LIBRARIES)
	
splashd.o : splashd.cc splashd.h gateway.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) splashd.cc
	
conf.o :  conf.cc conf.h util.cc util.h config.h linux.h http.h firewall.h defaults.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) conf.cc
	
util.o : util.cc util.h config.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) util.cc

linux.o : linux.cc linux.h http.h firewall.h util.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) linux.cc
	
gateway.o : gateway.cc gateway.h http.h http.cc conf.h conf.cc util.cc util.h firewall.cc firewall.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) gateway.cc
	
firewall.o : firewall.cc firewall.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) firewall.cc

http.o : http.cc http.h util.cc util.h mime.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) http.cc
	
websck.o : websck.h websck.cc gateway.h config.h
#	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) -Wno-pmf-conversions websck.cc
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) websck.cc

passive.o : gateway.h passive.cc firewall.cc firewall.h conf.h util.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) passive.cc

.PHONY: clean install install-local test test-local

clean :
	-rm -f $(EXECUTABLE) $(OBJECTS)

install :
	-cp -f $(EXECUTABLE) /usr/local/sbin/$(EXECUTABLE)
	-cp -f $(CONFFILE) /usr/local/etc/$(CONFFILE)
	-cp -f iptables/initialize.fw /usr/local/libexec/nocat/initialize.fw
	-cp -f iptables/access.fw /usr/local/libexec/nocat/access.fw
	
	
install-local: $(EXECUTABLE) nocat-local.conf iptables/initialize.fw

	-cp -f $(EXECUTABLE) /usr/local/sbin/$(EXECUTABLE)
	-cp -f nocat-local.conf /usr/local/etc/$(CONFFILE)
	-cp -f iptables/initialize.fw /usr/local/libexec/nocat/initialize.fw
	-cp -f iptables/access.fw /usr/local/libexec/nocat/access.fw
	
test :
	make
	make install
	/usr/local/sbin/$(EXECUTABLE)
	
test-local:
	make
	make install-local
	/usr/local/sbin/$(EXECUTABLE)
