# This makefile generated by Armando Baños Pascual

# variables

#OBJECTS = splashd.o conf.o util.o linux.o gateway.o firewall.o http.o websck.o passive.o
OBJECTS = splashd.o conf.o util.o linux.o gateway.o firewall.o http.o passive.o
INCLUDES = -I. -I/usr/include/glib-1.2 -I/usr/lib/glib/include -I/usr/include
WARNINGS = -Wall
LIBRARYPATH = -L/usr/lib -L/lib
#LIBRARIES = -lglib -lwebsockets
LIBRARIES = -lglib -lwebsockets -lcrypt
CC = g++
EXECUTABLE = splashd
CONFFILE = nocat.conf


DEBUG_YES = -g
DEBUG_NO =

DEBUG = $(DEBUG_YES)

OPTIMIZATIONS_0 =
OPTIMIZATIONS_1 = -O1
OPTIMIZATIONS_2 = -O2
OPTIMIZATIONS_3 = -O3
#optimization for size
OPTIMIZATIONS_s = -Os

OPTIMIZATIONS = $(OPTIMIZATIONS_0)

OUTPUT = -o $(EXECUTABLE)

# Rules

splashd : $(OBJECTS)
	$(CC) $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) $(OUTPUT) $(OBJECTS) $(LIBRARYPATH) $(LIBRARIES)
	
splashd.o : splashd.cc splashd.h gateway.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) splashd.cc
	
conf.o :  conf.cc conf.h util.cc util.h config.h linux.h http.h firewall.h defaults.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) conf.cc
	
util.o : util.cc util.h config.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) util.cc

linux.o : linux.cc linux.h http.h firewall.h util.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) linux.cc
	
gateway.o : gateway.cc gateway.h http.h http.cc conf.h conf.cc util.cc util.h firewall.cc firewall.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) gateway.cc
	
firewall.o : firewall.cc firewall.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) firewall.cc

http.o : http.cc http.h util.cc util.h mime.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) http.cc
	
#websck.o : websck.h websck.cc gateway.h config.h
#	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) websck.cc

passive.o : gateway.h passive.cc firewall.cc firewall.h conf.h util.h
	$(CC) -c $(INCLUDES) $(WARNINGS) $(OPTIMIZATIONS) $(DEBUG) passive.cc

.PHONY: clean install

clean :
	-rm -f $(EXECUTABLE) $(OBJECTS)

install :
	-cp -f $(EXECUTABLE) /usr/local/sbin/$(EXECUTABLE)
	-cp -f $(CONFFILE) /usr/local/etc/$(CONFFILE)
