#!/bin/sh /etc/rc.common
# "new" style init script
# Look at /lib/functions/ service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=80
APP=csicatd
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	service_start /usr/sbin/$APP
}
stop() {
      service_stop /usr/sbin/$APP
}
 
